### PR TITLE
Upload actions artifacts

### PR DESCRIPTION
**Pull request by thegu5**
pros:
- verifiable builds (know that the actions build and the stuff in releases - which can be edited - are exactly identical) (building on my own computer has a chance of not producing the exact same file)
- bleeding edge builds

cons:
- hi zedboy

### CODE REVIEW

**Comment by itsNMD404** [comment]
I wont be adding this as the action already uploads to the releases section. If you have concerns about builds clone the repo and figure out how to build it yourself

**Comment by itsNMD404** [comment]
> My concern is with the validity of the builds in the releases section - this would make it possible to prove that they're legitimate and that there isn't any malware or extra code in them. Building it on my own wouldn't deal with that.

in what way wouldnt it deal with that? you have the entirety of the source code open for you to see and package up? I dont think you understand

**Comment by itsNMD404** [comment]
> > > My concern is with the validity of the builds in the releases section - this would make it possible to prove that they're legitimate and that there isn't any malware or extra code in them. Building it on my own wouldn't deal with that.
> > 
> > 
> > in what way wouldnt it deal with that? you have the entirety of the source code open for you to see and package up? I dont think you understand
> 
> this change makes it so that you can _prove_ the files in the releases section were the ones built by the action (from the source code), and weren't edited after electron-builder uploaded them
> 
> I can't just build it myself, since my laptop's environment isn't going to be identical to the action's (maybe electron-builder had a small update, or an extra package was included due to a minor dependency version bump)
> 
> what doesn't make sense?

Im still struggling to understand why this is such an issue? Theres this wonderful thing called your browser i encourage you to use if you are that skeptical

**Comment by asger-finding** [comment]
@itsNMD404 

Having build files be automatically uploaded as artifacts from each action is incredibly useful.

The "build it yourself" attitude is dismissive, and frankly misses the point they're trying to make. As @thegu5 pointed out, there may be differences in the platform between you and the person needing their own build. They may be missing dependencies required to build the project, or use an entirely different desktop environment which prevents them from building.

Not only do artifacts allow the end user to match the checksum between the gh-action build file, and the file uploaded to the releases page, which ensures validity, but it also helps contributors to backpedal on their builds without having to checkout their git history first and for users to better debug any issues that may occur.

Github actions support Mac environments so you can sign, build and distribute `.dmg` files without any hassle.

Lastly, it allows maintainers to easily release and distribute nightly builds of their project — again also practical for end users, particularly power users, wanting to try the latest features without having to wait for an release or having to clone, setup, install and build the project themselves.

This is a process that I have long ago implemented in my own [electron project](https://github.com/asger-finding/anotherkrunkerclient). Artifacts are retained for (I believe) 90 days at no cost or storage cap if the repository is open-sourced.
It's six lines in the configuration that makes all the difference. The workflow time remains largely unchanged. You don't have to die on this hill. Really there isn't any hill to die on.

**Comment by itsNMD404** [comment]
Ill add it.

**Pull request closed without merging**
